-- ====================================================================
-- OBSOLETO — NO EJECUTAR. Se conserva solo como referencia histórica.
--
-- Este script creó las tablas `asistentes_2026` y `speakers_2026`, que ya no
-- forman parte del modelo vigente: el sitio escribe en `public.registrations`
-- y `public.speakers`. El esquema en uso está en `supabase_schema_updated.sql`
-- y los privilegios en `supabase_security_hardening.sql`.
--
-- Las políticas de lectura que tenía este archivo concedían SELECT sobre todas
-- las filas a cualquier usuario autenticado (`TO authenticated USING (true)`),
-- descritas como acceso «de administradores». Autenticarse no es ser
-- administrador: esas políticas se retiraron de este archivo para que no se
-- reutilicen. El modelo vigente no otorga lectura pública ni a `anon` ni a
-- `authenticated`; la consulta de registros se hace con credenciales de
-- administración desde el panel de Supabase.
--
-- Antes de ejecutar cualquier SQL sobre el proyecto, haz inventario de tablas,
-- políticas y privilegios existentes. No borres tablas a partir de este archivo.
-- ====================================================================

-- 1. Tabla de Asistentes (histórica)
CREATE TABLE IF NOT EXISTS public.asistentes_2026 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL,
    telefono TEXT,
    rol TEXT,
    dias TEXT,
    expectativas TEXT,
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) para asistentes
ALTER TABLE public.asistentes_2026 ENABLE ROW LEVEL SECURITY;

-- Política RLS: Permitir inserción pública (anon) desde la web
CREATE POLICY "Permitir insercion publica de asistentes"
ON public.asistentes_2026
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Sin política de SELECT: el navegador y las sesiones autenticadas solo pueden
-- insertar. La lectura queda reservada a los roles administrativos de Supabase.
REVOKE ALL PRIVILEGES ON TABLE public.asistentes_2026 FROM PUBLIC;
REVOKE ALL PRIVILEGES ON TABLE public.asistentes_2026 FROM anon, authenticated;
GRANT INSERT ON TABLE public.asistentes_2026 TO anon, authenticated;


-- 2. Tabla de Speakers / Propuestas de Charlas (histórica)
CREATE TABLE IF NOT EXISTS public.speakers_2026 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL,
    telefono TEXT,
    organizacion TEXT,
    bio TEXT,
    titulo_propuesta TEXT NOT NULL,
    descripcion_propuesta TEXT NOT NULL,
    nivel TEXT,
    modalidad TEXT,
    redes_sociales TEXT,
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) para speakers
ALTER TABLE public.speakers_2026 ENABLE ROW LEVEL SECURITY;

-- Política RLS: Permitir inserción pública (anon) desde la web
CREATE POLICY "Permitir insercion publica de speakers"
ON public.speakers_2026
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Misma restricción para las propuestas: solo inserción, nunca lectura pública.
REVOKE ALL PRIVILEGES ON TABLE public.speakers_2026 FROM PUBLIC;
REVOKE ALL PRIVILEGES ON TABLE public.speakers_2026 FROM anon, authenticated;
GRANT INSERT ON TABLE public.speakers_2026 TO anon, authenticated;
