-- ====================================================================
-- Script SQL para PyCon Panamá 2026 en Supabase
-- Ejecuta este script en el SQL Editor de tu proyecto de Supabase
-- ====================================================================

-- 1. Tabla de Asistentes
CREATE TABLE IF NOT EXISTS public.asistentes_2026 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL,
    telefono TEXT,
    rol TEXT,
    dias TEXT,
    expectativas TEXT,
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) para asistentes
ALTER TABLE public.asistentes_2026 ENABLE ROW LEVEL SECURITY;

-- Política RLS: Permitir inserción pública (anon) desde la web
CREATE POLICY "Permitir insercion publica de asistentes"
ON public.asistentes_2026
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Política RLS: Permitir lectura solo a usuarios autenticados (administradores)
CREATE POLICY "Permitir lectura solo a autenticados"
ON public.asistentes_2026
FOR SELECT
TO authenticated
USING (true);


-- 2. Tabla de Speakers / Propuestas de Charlas
CREATE TABLE IF NOT EXISTS public.speakers_2026 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL,
    telefono TEXT,
    organizacion TEXT,
    bio TEXT,
    titulo_propuesta TEXT NOT NULL,
    descripcion_propuesta TEXT NOT NULL,
    nivel TEXT,
    modalidad TEXT,
    redes_sociales TEXT,
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) para speakers
ALTER TABLE public.speakers_2026 ENABLE ROW LEVEL SECURITY;

-- Política RLS: Permitir inserción pública (anon) desde la web
CREATE POLICY "Permitir insercion publica de speakers"
ON public.speakers_2026
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Política RLS: Permitir lectura solo a usuarios autenticados (administradores)
CREATE POLICY "Permitir lectura solo a autenticados"
ON public.speakers_2026
FOR SELECT
TO authenticated
USING (true);
