blank_issues_enabled: true
contact_links:
  - name: Consultas sobre PyCon Panamá
    url: mailto:pyconpanama@gmail.com
    about: Para consultas sobre el evento que no sean errores o cambios del sitio web.
